### ISSUE TITLE
CMake error: the source directory "..." does not appear to contain CMakeList.txt

### ISSUE THREAD

**Issue by PokerN** [martinjrobins/Aboria#23]
Hi, I really admire your work, and want to try your  c++ library. However, I'm stuck with the first example you provided in “Installation and Getting Started”. I did exactly what you told. But I don't understand the meaning of "Note that this assumes that the Aboria repository is in your current directory, which it will be if you just cloned the repo using the git command above". So I cloned the repo, and saved the two file "getting_started.cpp" and "CMakeLists.txt", placed them with the repo in the same directory. It looks like below:

**.
 .. 
Aboria 
CMakeLists.txt 
getting_started.cpp**

When I entered the command “cmake .”, I got the error "the source directory "..." does not appear to contain CMakeList.txt".
I am not familiar with CMAKE, and eager to get your help.  Thank you very much.
My system is ubuntu 16.04.

**Comment by martinjrobins** [comment]
Hi @PokerN. Your directory looks good. This directory should be your current working directory, so that when you type `cmake .`, the `.` refers to the directory with the `CMakeLists.txt` file. This is the error that cmake is giving you: that the directory you are giving it does not contain a `CMakeLists.txt`.

**Comment by PokerN** [comment]
Thank you very much! I will learn about cmake. Once I figure it out, I will give a clear description of my problem below.
