### ISSUE TITLE
Question: is Aboria::Particles<>'s design similar to std::variant?

### ISSUE THREAD

**Issue by Char-Aznable** [martinjrobins/Aboria#28]
What's the programming pattern behind Aboria::Particles<>'s capability to handle arbitrary number of types, e.g., position, velocity, id...? Just by skimming the code I found that it's kinda designed similarly to std::variant in c++17 or boost::variant -- just curious, is my guess correct?

**Comment by martinjrobins** [comment]
No, its more based on `boost::zip_iterator` or `thrust::zip_iterator`. I wanted to see if you could do a similar thing, but at the container level. That is have a vector container that was really just a zip'ed collection of other vectors (so each variable in Aboria would have its own lower-level vector container). Once the user supplies the type list of variables, you just use some meta-programming techniques to build up your zip container. Aboria enforces that the type list of variables is made up of unique types, so then you can use `get<variable>(i)` functions to access individual variables.

Good news is that you can build up this zip container easily enough, bad news is that its not 100% STL compatible, in much the same reason that  std::vector<bool> is not compatible because it uses proxy references. Note that the `value_type` of this container is something like `std::tuple<T1,T2,T3,...>`, but the `reference` is `std::tuple<T1&,T2&,T3&,...>`, so the `reference` type is not a reference of the `value_type`. But saying that, it does work fine for most situations.

**Comment by Char-Aznable** [comment]
That makes sense. Thanks for the explanation.
