### ISSUE TITLE
Passing a Particle Label to a Function

### ISSUE THREAD

**Issue by JabirSS** [martinjrobins/Aboria#30]
Dear Dr. Robinsons,

I am trying to create class member functions to which I would pass a particle label, or labels, do some work (featuring among other things accumulator functions) on its values and return a particle label, e.g. `p[a]=function(p[b]);`

I am unable to do this as I can't figure out a way to get the label data type. I tried using a template function but the compiler threw a insanely-long error related to boost::proto. 

I'm not sure whether my logic here is right or not, but my motivation for trying to do this is to avoid creating particle labels within my function/object (expensive?), since I guess my other option would be try and pass the particle container to my function by reference and then create the labels within my functions.

I would much appreciate your thoughts on this.

Best regards,

Jabir

**Comment by JabirSS** [comment]
I just wanted to add that I am aware of the possibility of wrapping a C++ function object as lazy Aboria functions as per the symbolic Level 3 API but I noticed some problems with that method such as being unable to directly use such functions within others, so I'm just aiming for more flexibility.

**Comment by martinjrobins** [comment]
Hi @JabirSS. Aboria has both symbols:

```cpp
Symbol<position> p;
```
and labels:

```
Label<0,MyParticles> a(particles);
```
You can see the types of these objects above (where `MyParticles` is the type of your particle container/set, and `particles` is an object of type `MyParticles`.

Now say you did this:

```
auto something = p[a];
```

The type of `something` is going to be long and complicated, because `p[a]` is an expression template, and not designed to be held as a object. Here I have used `auto` to let the compiler deduce the correct type.

If you wanted to pass `p[a]` into a function (and get another expression out) you would have to do the same (let the compiler deduce the type), like so:

```
template <typename T>
auto my_function(T& p_a) {
  //do something
  return something;
}
```

But you probably don't want to do that, passing expression templates around is a sure-fire recipe for madness (i.e. the long and messy compiler errors). If I were you I would pass the `Label` object into the function instead and create the symbol inside that function:

```
void my_function(Label<0,MyParticles>& a) {
  Symbol<position> p;
  //do something with p[a] if you wish
}
```

`Symbol` objects are lightweight to construct, `Label` objects *might* not be lightweight, sometimes they can allocate memory to deal with aliased expressions, hence my suggestion of passing in just the `Label`.

Does this solve your question?

**Comment by JabirSS** [comment]
Dear @martinjrobins ,

Thanks a lot for your quick reply! This does clarify quite a bit! I'm still a beginner with C++ so please excuse all the newbie questions :).

One last thing... Do you recommend doing something like:


```
//create particle container, labels a and b, symbols and ABORIA_VARIABLEs globally etc..

auto my_function(Label<0,MyParticles>& a) {
 Symbol<position> p;
  //do something with p[a]
return p[a];
}

int main() {
Symbol<position> p;
p[b]=my_function(a)
//...
}
```

I know this is almost exactly like what you have warned against above with regards to passing expression templates around, but what about overhead? I only plan to use it in small parts of the code.

**Comment by martinjrobins** [comment]
There would be no overhead doing this, but if you are going in that direction you might be able to make it fully generic with a lambda function like so:

```
int main() {
  // setup stuff ...
  Label<0,MyParticles>& a(particles1);
  Label<0,MyParticles>& b(particles2);
  Symbol<position> p;
  auto mult_by_three = [&] (auto& p_a) { return 3 * p[a] };
  p[b] = mult_by_three(p[a]);
```

For small bits of abstraction like this lambda function, you should be ok. For anything more complicated, you could always ditch the symbolic expression API of Aboria and go for the low-level API, this is much easier to integrate into bigger C++ projects.

**Comment by JabirSS** [comment]
Perfect! Thanks a lot!
